name: Deploy to Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn
      - name: Create OpenVPN configuration file
        run: |
          echo ${{ secrets.OPENVPN_FILE }} | base64 --decode > openvpn.ovpn
      - name: Connect OpenVPN
        run: |
          sudo openvpn --config openvpn.ovpn --log /tmp/openvpn.log --verb 4 --daemon
          sleep 10
      - name: Show OpenVPN logs
        run: cat /tmp/openvpn.log || echo "Log not found"
      - name: Run command
        run: |
          ping -c 4 192.168.0.1
      - name: Disconnect OpenVPN
        run: |
          pkill openvpn
